### ISSUE TITLE
Multi-dataset training config

### ISSUE THREAD

**Issue by haoyayuzzzz** [ViTAE-Transformer/ViTPose#56] opened 2022-11-30 05:15 UTC
Hello, the author. I learn a lot from your work. Thank you for sharing. I want to know when can the config of multi-dataset training  and relative code be updated?

**Comment by nini0919** [comment] 2022-12-10 03:38
Hello author, when will your multi-task training code be open source?I really look forward to hearing from you!!

**Comment by Annbless** [comment] 2023-02-13 03:05
Hi, the training code and the corresponding logs have been uploaded. I will close this issue since it seems the issue is fixed. If you have some further questions, please feel free to re-open it.

**Closed by Annbless** 2023-02-13 03:05 UTC
